### ISSUE TITLE
Hi-Res images pointing to 1000px variant

### ISSUE THREAD

**Issue by cpietsch** [riksantikvarieambetet/VIKUS-Viewer-Nationalmuseum#1]
Hi, just found out about the study and saw that the hi-res images are pointing to the same files as the medium images (1000px) e.g. http://kontoret.delorean.se/raa/data/data/4096/19257.jpg .
Is that intended ? Otherwise you could remove the "big" entry from the config.json.

**Comment by Abbe98** [comment]
Removed duplicate big images.
